sudo: required
services:
  - docker

before_install:
  - docker build -t runehoivik/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true runehoivik/docker-react npm run test -- --coverage  